### ISSUE TITLE
Add version command

### ISSUE THREAD

**Issue by voor** [pivotal/image-relocation#41]
I want to know what version of `irel` I have installed on my system and whether I need to upgrade.

**Comment by glyn** [comment]
I propose to add a `--version` flag which is the normal way to support CLI version in Cobra.

## Examples
```
./irel --version
irel version 0.7.0-snapshot (41624eb24559bb438ef2f5d1ae53f16d01e53813)
```

The flag is described in the online help, thus:
```
./irel -h
irel is a tool for relocating container images

Usage:
  irel [flags]
  irel [command]

Available Commands:
  <snip>

Flags:
  -h, --help      help for irel
      --version   display CLI version

Use "irel [command] --help" for more information about a command.
```

**Comment by glyn** [comment]
This feature was included in https://github.com/pivotal/image-relocation/releases/tag/v0.7.
