### ISSUE TITLE
Return / expose image manifest size

### ISSUE THREAD

**Issue by radu-matei** [pivotal/image-relocation#9]
As part of the relocation process, among the information returned is the manifest size.

```
2019/04/25 22:05:21 pushed blob: sha256:94e814e2efa8845d95b2112d54497fbad173e45121ce9255b93401392f538499
2019/04/25 22:05:21 pushed blob: sha256:63366dfa0a5076458e37ebae948bc7823bab256ca27e09ab94d298e37df4c2a3
2019/04/25 22:05:21 pushed blob: sha256:041d4cd74a929bc4b66ee955ab5b229de098fa389d1a1fb9565e536d8878e15f
2019/04/25 22:05:21 pushed blob: sha256:6e1bee0f8701f0ae53a5129dc82115967ae36faa30d7701b195dfc6ec317a51d
2019/04/25 22:05:28 pushed blob: sha256:898c46f3b1a1f39827ed135f020c32e2038c87ae0690a8fe73d94e5df9e6a2d6
2019/04/25 22:05:28 <repository> digest: sha256:f2557f94cac1cc4509d0483cb6e302da841ecd6f82eb2e91dc7ba6cfd0c580ab 
size: 1150
```

Is is reasonable to expect this library to expose the pushed manifest's size?

Thanks!

**Comment by glyn** [comment]
The logs above are printed by ggcr and I think ggcr would need reworking a little to surface the raw manifest size. To motivate this, please could you say what use you would like to make of the raw manifest size.

**Comment by radu-matei** [comment]
Context:

I'm using this library (with the difference that all referenced images are pushed to the same repository, under different tags), together with [`deislabs/oras`](https://github.com/deislabs/oras), to push all images and the bundle file to an OCI registry.

Currently, upstream `deislabs/oras` creates an [image config manifest](https://github.com/opencontainers/image-spec/blob/master/config.md), which only contains the layers of the objects pushed through `oras` - which in my case is the CNAB bundle file.

I wanted to modify this, and push [an OCI image index](https://github.com/opencontainers/image-spec/blob/master/image-index.md), so that the resulting end manifest contains the bundle, together with all referenced images.

See https://github.com/radu-matei/coras for an example of how this used. (Keep in mind this is just an experiment).

That being said, I can directly use `github.com/google/go-containerregistry` to get the manifest size, so this is no longer a direct need from this library.

Thanks a lot for the awesome work done here!

**Comment by glyn** [comment]
Thanks @radu-matei. Actually, I'd prefer to expose the image size as it's better to encapsulate `github.com/google/go-containerregistry` rather than require users to use it directly. What method are you using to get the manifest size?

**Comment by radu-matei** [comment]
In a nutshell (see [example here](https://github.com/radu-matei/coras/blob/master/pkg/coras/index_utils.go)), once you get a reference to an image, you have access to all fields in [v1.Image](https://github.com/google/go-containerregistry/blob/master/pkg/v1/image.go#L22:6), and you can calculate the size of the raw manifest:

```
	ref, err := name.ParseReference(imageRef)
	if err != nil {
		return nil, fmt.Errorf("cannit parse image reference: %v", err)
	}

	im, err := remote.Image(ref, remote.WithAuth(auth))
	if err != nil {
		return ocispec.Descriptor{}, fmt.Errorf("cannot get image: %v", err)
	}

	rm, err := im.RawManifest()
	if err != nil {
		return ocispec.Descriptor{}, fmt.Errorf("cannot get manifest: %v", err)
	}

    fmt.Printf("raw manifest size: %v", int64(len(rm)))
```

**Comment by glyn** [comment]
Thanks. Implementation underway ^^.

**Comment by glyn** [comment]
@radu-matei I've been discussing the requirements with @fbiville who has been reviewing the PR. It would be helpful to know what use you will make of the image manifest size. Will you use it, for example, to populate the image size fields in the CNAB manifest?
